### ISSUE TITLE
maven依赖有问题

### ISSUE THREAD

**Issue by bad7890** [JackZhu426/ElysiumMall#3]
有的包依赖版本没有写
有的类需要另外导包
请问我需要做什么处理才能正常运行?

**Comment by Mr-Robot-001** [comment]
刚开始空的仓库300星，前几天explore看见500+星，沉了一段时间，今天又在explore出现，少了200个星，怎么总是在explore看到= =
综合上述，应该不能运行吧

**Comment by Mr-Robot-001** [comment]
刚开始空的仓库200星，前几天explore看见500+星，沉了一段时间，今天又在explore出现，少了200个星，怎么总是在explore看到= =
综合上述，应该不能运行吧
